name: CI

on: [push, pull_request]

env:
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.19.3
            otp: 28.1.1
            rebar3: 3.25.1
            lint: true

          - elixir: 1.18.4
            otp: 27.3.4.6
            rebar3: 3.25.1

    steps:
      - uses: actions/checkout@v4

      - name: Setup Beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Erlang Tests
        run: |
          make distclean
          make erlang-mk
          make ct

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check Formatting
        if: ${{ matrix.lint }}
        run: mix format --check-formatted

      - name: Elixir Tests
        run: mix test

      - name: Logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ct-logs-${{matrix.erlang}}
          path: logs/*
  
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Beam
        id: setupBeam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.19.3
          otp-version: 28.1.1

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.otp-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
  
      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Dialyzer
        run: mix dialyzer --format github