name: CI

on: [push, pull_request]

env:
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO: Remove -rc.0 once Elixir 1.17 is released
          # TODO: Lint in this version once Elixir 1.17 is released
          - elixir: "1.17.0-rc.0"
            otp: "27.0"

          - elixir: "1.16.3"
            otp: "26.2.5"
            lint: true

          - elixir: "1.15.8"
            otp: "26.2.5"

          - elixir: "1.14.5"
            otp: "25.3.2.12"

          - elixir: "1.13.4"
            otp: "24.3.4.17"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Erlang Tests
        run: |
          make distclean
          make erlang-mk
          make ct

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v1
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check Formatting
        if: ${{ matrix.lint }}
        run: mix format --check-formatted

      - name: Elixir Tests
        run: mix test

      - name: Logs
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: ct-logs-${{matrix.erlang}}
          path: logs/*
  
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Beam
        id: setupBeam
        uses: erlef/setup-beam@v1
        with:
          # TODO: Update to OTP 27.0 and Elixir 1.17 once Elixir 1.17 is released
          elixir-version: 1.16.3
          otp-version: 26.2.5

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v1
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.otp-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
  
      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Dialyzer
        run: mix dialyzer --format github